#ifndef BACKWARD_COMPATABILITY_INCLUDE
#define BACKWARD_COMPATABILITY_INCLUDE

#if MOZVER == 191
	#include "xpcom/nsCOMPtr.h"
	#include "xpcom/nsStringEnumerator.h"
    #include "content/nsIDocument.h"
	#include "js/jsapi.h"
	#include "js/jsobj.h"
	#include "dom/nsIDOMHTMLElement.h"
	#include "string/nsEmbedString.h"
    #include "xpcom/nsServiceManagerUtils.h"
    #include "caps/nsIScriptSecurityManager.h"
    #include "nspr/prtypes.h"
    #include "xpcom/nscore.h"
    #include "xulapp/nsXULAppAPI.h" 
    #include "embed_base/nsEmbedAPI.h"
    #include "widget/nsIBaseWindow.h" 
    #include "docshell/nsIWebNavigation.h" 
    #include "xpcom/nsIInterfaceInfoManager.h"
    #include "xpcom/nsIInterfaceInfo.h"
    #include "xpcom/nsIInterfaceRequestorUtils.h"
    #include "xpcom/xptinfo.h"
	#include "dom/nsIScriptGlobalObject.h"
	#include "dom/nsIScriptContext.h"
	#include "xpcom/xptcall.h"
	#include "necko/nsICookieManager2.h"
#else
	#include "nsCOMPtr.h"
	#include "nsIStringEnumerator.h"
        #include "nsIDocument.h"
	#include "jsapi.h"
	#include "jsobj.h"
	#include "nsIScriptGlobalObject.h"
	#include "nsIDOMHTMLElement.h"
	#include "nsEmbedString.h"
        #include "nsServiceManagerUtils.h"
        #include "nsIScriptSecurityManager.h"
        #include "prtypes.h"
        #include "nscore.h"
        #include "nsXULAppAPI.h" 
        #include "nsEmbedAPI.h"
        #include "nsIBaseWindow.h" 
        #include "nsIWebNavigation.h" 
        #include "nsIInterfaceInfoManager.h"
        #include "nsIInterfaceInfo.h"
        #include "nsIInterfaceRequestorUtils.h"
        #include "xptinfo.h"
	#include "nsIScriptContext.h"
	#include "xptcall.h"
	#include "nsICookieManager2.h"
#endif


#endif
